---
- name: download and unzip vault
  unarchive:
    src: https://releases.hashicorp.com/vault/0.8.3/vault_0.8.3_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes

- name: Write vault systemd service file
  copy: src=vault.service dest=/lib/systemd/system/vault.service mode=u=rw,g=r,o= owner=root group=root

- name: Add VAULT_ADDR variable to be sourced on login
  blockinfile:
    path: /home/ec2-user/.bash_profile
    block: |
      export VAULT_ADDR="http://127.0.0.1:8200"
      export VAULT_SKIP_VERIFY=1
      
- name: Write vault config file
  template: src=vault.conf.j2 dest=/etc/vault.conf mode=u=rw,g=r,o=


- name: Enable and start vault service
  systemd:
    name: vault.service
    state: started
    enabled: True
